Exercise.create(name: "Squat")
Exercise.create(name: "Bench Press")
Exercise.create(name: "Deadlift")
Exercise.create(name: "Bicep Curl")
Exercise.create(name: "Skullcrusher")
Exercise.create(name: "Shoulder Press")
Exercise.create(name: "Pull Up")
Exercise.create(name: "Push Up")
Exercise.create(name: "Power Clean")

